"use client";
import Image from "next/image";
import Link from "next/link";
import { FormEvent,useCallback,useEffect,useMemo,useState } from "react";
import { ThemeToggle } from "./theme-toggle"; import { InstallButton } from "./install-button"; import { LineChart } from "./line-chart"; import type { MarketSnapshot } from "@/lib/types";
const QUICK=["AAPL","MSFT","NVDA","SPY","QQQ","INDA","EZA","EWZ"];
const NAMES:Record<string,string>={AAPL:"Apple",MSFT:"Microsoft",NVDA:"NVIDIA",SPY:"S&P 500 ETF",QQQ:"Nasdaq 100 ETF",INDA:"India ETF",EZA:"South Africa ETF",EWZ:"Brazil ETF"};
const WATCH_KEY="iwas-findex-watchlist";
export function Dashboard(){const [symbol,setSymbol]=useState("AAPL"),[query,setQuery]=useState("AAPL"),[snapshot,setSnapshot]=useState<MarketSnapshot|null>(null),[loading,setLoading]=useState(true),[error,setError]=useState<string|null>(null),[watch,setWatch]=useState<string[]>(["AAPL","MSFT","NVDA","SPY"]);
useEffect(()=>{const timer=window.setTimeout(()=>{try{const raw=localStorage.getItem(WATCH_KEY);if(raw){const parsed=JSON.parse(raw);if(Array.isArray(parsed))setWatch(parsed.filter(x=>typeof x==="string").slice(0,8));}}catch{}},0);return()=>window.clearTimeout(timer);},[]);
const load=useCallback(async(next:string)=>{const clean=next.trim().toUpperCase();if(!clean)return;setLoading(true);setError(null);try{const r=await fetch(`/api/market?symbol=${encodeURIComponent(clean)}`);const b=await r.json() as MarketSnapshot|{error:string};if(!r.ok||"error" in b)throw new Error("error" in b?b.error:"Request failed.");setSnapshot(b);setSymbol(b.symbol);setQuery(b.symbol);}catch(e){setError(e instanceof Error?e.message:"Unable to load market data.");}finally{setLoading(false)}},[]);
useEffect(()=>{const initial=new URLSearchParams(window.location.search).get("symbol")||"AAPL";const timer=window.setTimeout(()=>void load(initial),0);return()=>window.clearTimeout(timer);},[load]);
const submit=(e:FormEvent)=>{e.preventDefault();void load(query)};const saved=watch.includes(symbol);const toggleWatch=()=>{const next=saved?watch.filter(x=>x!==symbol):[symbol,...watch.filter(x=>x!==symbol)].slice(0,8);setWatch(next);localStorage.setItem(WATCH_KEY,JSON.stringify(next));};const rows=useMemo(()=>snapshot?.candles.slice(-8).reverse()??[],[snapshot]);const delta=snapshot?snapshot.forecast.nextClose-snapshot.latest.close:0;const fp=snapshot&&snapshot.latest.close?delta/snapshot.latest.close*100:0;const positive=snapshot&&snapshot.latest.change>=0;
return <main>
<header className="site-header"><div className="shell header-inner"><a className="brand" href="#overview"><Image src="/brand-mark.svg" alt="iWas Findex" width={42} height={42} priority/><span><strong>iWas</strong> Findex</span></a><nav className="primary-nav"><a href="#overview">Overview</a><a href="#markets">Markets</a><a href="#forecast">Forecast</a><Link href="/downloads">Downloads</Link></nav><div className="header-actions"><ThemeToggle/><InstallButton/></div></div></header>
<section className="hero shell" id="overview"><div><p className="eyebrow">Cross-platform market intelligence</p><h1>Make faster decisions with evidence you can inspect.</h1><p className="hero-copy">Analyse market movement, review a transparent trend baseline, save a watchlist and install the same workspace on web, mobile and desktop.</p><div className="hero-actions"><a className="primary-action" href="#workspace">Open workspace</a><Link className="secondary-action" href="/downloads">Get the apps</Link></div><div className="trust-row"><span><i/>Installable PWA</span><span><i/>Cross-browser extension</span><span><i/>Demo-safe by default</span></div></div><aside className="hero-terminal"><div className="terminal-topline"><span className="terminal-product"><Image src="/brand-mark.svg" alt="" width={24} height={24}/>LIVE WORKSPACE</span><span className="terminal-status">CONNECTED</span></div><div className="terminal-symbol">{snapshot?.symbol??symbol}</div><div className="terminal-price">{snapshot?money(snapshot.latest.close):"--"}</div><div className={snapshot&&snapshot.latest.change<0?"negative":"positive"}>{snapshot?`${signed(snapshot.latest.change)} · ${signed(snapshot.latest.changePercent)}%`:"Loading"}</div><div className="mini-bars">{(snapshot?.candles.slice(-12)??[]).map((c,i)=><span key={i} style={{height:`${28+(c.close%65)}%`}}/> )}</div><div className="terminal-footer"><span>Mode</span><strong>{snapshot?.mode??"Demo"}</strong></div></aside></section>
<section className="workspace shell" id="workspace"><div className="workspace-heading"><div><p className="section-kicker">Market workspace</p><h2>One screen for signal, context and distribution</h2></div><div className="workspace-meta"><span className="live-dot"/>Updated {snapshot?new Date(snapshot.generatedAt).toLocaleTimeString([], {hour:"2-digit",minute:"2-digit"}):"--"}</div></div>
<div className="toolbar card" id="markets"><form className="symbol-form" onSubmit={submit}><label htmlFor="symbol">Ticker symbol</label><div className="input-row"><span className="search-icon">⌕</span><input id="symbol" value={query} onChange={e=>setQuery(e.target.value)} maxLength={15} autoComplete="off"/><button type="submit" disabled={loading||!query.trim()}>{loading?"Loading":"Analyse"}</button></div><small>US-listed equity or ETF ticker</small></form><div className="quick-symbols">{QUICK.map(s=><button key={s} className={`symbol-chip ${s===symbol?"active":""}`} onClick={()=>void load(s)} disabled={loading}>{s}</button>)}</div><button className={`watch-button ${saved?"active":""}`} onClick={toggleWatch}>{saved?"★ Saved":"☆ Watch"}</button></div>
{error&&<div className="error-banner" role="alert">{error}</div>}{snapshot?.message&&<div className="info-banner">{snapshot.message}</div>}
<div className="metrics-grid"><Metric label="Latest close" value={snapshot?money(snapshot.latest.close):"--"} sub={snapshot?.latest.date??"Awaiting data"}/><Metric label="Daily movement" value={snapshot?`${signed(snapshot.latest.change)} (${signed(snapshot.latest.changePercent)}%)`:"--"} sub="Versus prior trading day" cls={snapshot?(positive?"positive":"negative"):""}/><Metric label="Session range" value={snapshot?`${money(snapshot.latest.dayLow)} to ${money(snapshot.latest.dayHigh)}`:"--"} sub="Daily low to high"/><Metric label="Volume" value={snapshot?compact(snapshot.latest.volume):"--"} sub="Latest reported session"/></div>
<div className="analysis-grid" id="forecast"><article className="card chart-card"><div className="card-heading"><div><p className="section-label">Price history</p><h3>{snapshot?.symbol??symbol} closing trend</h3></div><span className={`mode-badge ${snapshot?.mode??"demo"}`}>{snapshot?.mode==="live"?"Live provider":"Demo series"}</span></div>{snapshot?<LineChart candles={snapshot.candles} forecast={snapshot.forecast.nextClose}/>:<div className="chart-skeleton"/>}<div className="chart-legend"><span><i className="legend-line"/>Historical close</span><span><i className="legend-dash"/>One-step projection</span></div></article><aside className="card forecast-card"><div><p className="section-label">Baseline forecast</p><h3>Next-close projection</h3></div><div className="forecast-number">{snapshot?money(snapshot.forecast.nextClose):"--"}</div><div className={`forecast-change ${delta>=0?"positive":"negative"}`}>{snapshot?`${signed(delta)} (${signed(fp)}%)`:"Awaiting data"}</div><dl className="model-stats"><div><dt>Direction</dt><dd>{snapshot?(Math.abs(fp)<0.01?"Flat":fp>0?"Up":"Down"):"--"}</dd></div><div><dt>Model fit, R²</dt><dd>{snapshot?snapshot.forecast.rSquared.toFixed(3):"--"}</dd></div><div><dt>Residual error</dt><dd>{snapshot?money(snapshot.forecast.residualError):"--"}</dd></div><div><dt>30-day volatility</dt><dd>{snapshot?`${snapshot.forecast.volatility.toFixed(2)}%`:"--"}</dd></div></dl><div className="forecast-note"><span>i</span><div>This is a transparent linear trend baseline, not a guarantee or trading recommendation.</div></div></aside></div>
<div className="lower-grid"><article className="card table-card"><div className="card-heading"><div><p className="section-label">Recent sessions</p><h3>Daily OHLCV data</h3></div><button className="symbol-chip" onClick={()=>void load(symbol)} disabled={loading}>Refresh</button></div><div className="table-scroll"><table><thead><tr><th>Date</th><th>Open</th><th>High</th><th>Low</th><th>Close</th><th>Volume</th></tr></thead><tbody>{rows.map(r=><tr key={r.date}><td>{r.date}</td><td>{money(r.open)}</td><td>{money(r.high)}</td><td>{money(r.low)}</td><td>{money(r.close)}</td><td>{compact(r.volume)}</td></tr>)}</tbody></table></div></article><aside className="card watchlist-card"><div className="card-heading"><div><p className="section-label">Saved instruments</p><h3>Your watchlist</h3></div><span className="count-pill">{watch.length} symbols</span></div><div className="watchlist-stack">{watch.map(s=><button key={s} className={`watch-row ${s===symbol?"current":""}`} onClick={()=>void load(s)}><span className="ticker-avatar">{s.slice(0,2)}</span><span className="watch-copy"><strong>{s}</strong><small>{NAMES[s]??"Saved instrument"}</small></span><span>→</span></button>)}</div><Link className="download-callout" href="/downloads"><span className="callout-icon">↓</span><span><strong>Cross-platform downloads</strong><small>Web, browser extension and installable app</small></span><span>→</span></Link></aside></div></section>
<footer className="shell footer"><span className="footer-brand"><Image src="/brand-mark.svg" alt="" width={27} height={27}/>iWas Findex</span><span>For research and demonstration only. Not financial advice. · <Link href="/privacy">Privacy</Link></span></footer></main>}
function Metric({label,value,sub,cls=""}:{label:string;value:string;sub:string;cls?:string}){return <article className="card metric-card"><p>{label}</p><strong className={cls}>{value}</strong><span>{sub}</span></article>}
function money(v:number){return new Intl.NumberFormat("en-US",{style:"currency",currency:"USD",maximumFractionDigits:2}).format(v)}
function compact(v:number){return new Intl.NumberFormat("en-US",{notation:"compact",maximumFractionDigits:1}).format(v)}
function signed(v:number){return `${v>0?"+":v<0?"-":""}${Math.abs(v).toFixed(2)}`}
